services:
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    networks:
      - elk_jaeger_network

  logstash:
    image: logstash:${LOGSTASH_VERSION}
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "5044:5044"
      - "5959:5959"
    networks:
      - elk_jaeger_network

  kibana:
    image: kibana:${KIBANA_VERSION}
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - elk_jaeger_network

  jaeger-agent:
    image: jaegertracing/jaeger-agent:${JAEGER_VERSION}
    container_name: jaeger-agent
    command: ["--reporter.grpc.host-port=${JAEGER_COLLECTOR_HOST}:${JAEGER_COLLECTOR_PORT}"]
    ports:
      - "${JAEGER_AGENT_PORT}:6831"
    networks:
      - elk_jaeger_network

  jaeger-collector:
    image: jaegertracing/jaeger-collector:${JAEGER_VERSION}
    container_name: jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      - ES_USERNAME=${ELASTICSEARCH_USERNAME}
      - ES_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "${JAEGER_COLLECTOR_PORT}:14268"
    networks:
      - elk_jaeger_network

  jaeger-query:
    image: jaegertracing/jaeger-query:${JAEGER_VERSION}
    container_name: jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      - ES_USERNAME=${ELASTICSEARCH_USERNAME}
      - ES_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "${JAEGER_QUERY_PORT}:16686"
    networks:
      - elk_jaeger_network

volumes:
  elasticsearch_data:

networks:
  elk_jaeger_network:
    driver: bridge
